{% set name = "micropython" %}
{% set version = "1.28.0" %}
{% set build = 2 %}
{% set sha256 = "4e43c59657b8da33b4bc503509a827cc3ea6cb66c446475c57776cf4467ba215" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://github.com/micropython/micropython/releases/download/v{{ version }}/micropython-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make       # [unix]
    - pkgconfig  # [unix]
    - python *   # [win]
  host:
    - libffi  # [unix]

test:
  commands:
    - micropython -c "print('hello')"

about:
  home: https://micropython.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python for microcontrollers
  description: |
    MicroPython is a lean and efficient implementation of the Python 3
    programming language that includes a small subset of the Python standard
    library and is optimised to run on microcontrollers and in constrained
    environments.
  dev_url: https://github.com/micropython/micropython

extra:
  recipe-maintainers:
    - davidbrochart
