{% set name = "micropython" %}
{% set version = "1.21.0" %}
{% set build = 0 %}
{% set sha256 = "f590fc084a48ed69bec69adef3287867f8b5a06613c0785583a7c1e215e68d7b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/micropython/micropython/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - wget
    - unzip
  host:
    - libffi
    - pkgconfig

test:
  commands:
    - micropython -c "print('hello')"

about:
  home: https://micropython.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python for microcontrollers
  description: |
    MicroPython is a lean and efficient implementation of the Python 3
    programming language that includes a small subset of the Python standard
    library and is optimised to run on microcontrollers and in constrained
    environments.
  dev_url: https://github.com/micropython/micropython

extra:
  recipe-maintainers:
    - davidbrochart
